### ISSUE TITLE
Damage not being applied correctly

### ISSUE THREAD

**Issue by tthomsen** [dmdorman/hero6e-foundryvtt#508] opened 2023-12-18 04:35 UTC
One of my players noticed this during our game this weekend. 12 body and 24 stun is rolled but when it is applied to the monster it's only 10 body 20 stun. It looks like the half die is being dropped. We noticed the same issue applies to attacks that use a pip.

![image_2023_12_17T05_59_52_942Z2](https://github.com/dmdorman/hero6e-foundryvtt/assets/277447/38332ab3-9833-4e8a-ae5d-fab322bf9831)

**Comment by phBalance** [comment] 2023-12-24 21:03
Confirmed the damage reported and dealt doesn't seem to match up. 9 BODY 18 STUN reported being done. 8 BODY 16 STUN reported on damage card with 1 resistant defense dropping the damage to 7 BODY and 13 STUN. Character sheet confirms 7 BODY and 13 STUN received.
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/29824554/038385b1-bd7f-4ea0-b78a-c77eb356b085)
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/29824554/2235683b-28c3-487a-a1cc-04f28ff406bc)

It would appear that there are 2 questions to answer:
1. Is defense is not applied correctly? It appears that non resistant ED is being applied against STUN despite it being a killing attack
2. What happened to the damage reported in the damage roll card?

**Comment by phBalance** [comment] 2023-12-24 21:11
Looks like I didn't know the rules so well. WRT defense, regular defense can be applied to STUN if there is matching resistant defense (5e p.410).

**Comment by phBalance** [comment] 2024-01-01 18:21
Additional note that rolling attacks with no dice (say 1 pip attack) will crash.

**Comment by aeauseth** [comment] 2024-01-08 08:23
Looks like STUN for multiple dice terms was fixed in 3.0.54, but still issue with body and 1/2 dice.

**Comment by phBalance** [comment] 2024-02-03 00:06
Should be resolved with https://github.com/dmdorman/hero6e-foundryvtt/pull/627

**Closed by phBalance** 2024-02-03 00:06 UTC
Labels: bug

**Comment by rivethead42** [comment] 2024-02-03 00:45
Awesome!
