### ISSUE TITLE
Not spending END for characteristics

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#332] opened 2023-09-03 01:34 UTC
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/e238e127-ec39-4928-95ba-21f84b46ae4a)

**Comment by phBalance** [comment] 2024-01-12 00:19
This works as of 3.0.54. The functionality was basically there but there was a crash in this code fixed in the last release. Perhaps that was the cause.

**Closed by phBalance** 2024-01-12 00:19 UTC
